import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import AuthContext from '@/context/auth-context';
import ThemeContext from '@/context/theme-context';
import ToasterContext from '@/context/toast-context';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeContext attribute="class" defaultTheme="dark" enableSystem disableTransitionOnChange>
          <AuthContext>
            {children}
            <ToasterContext />
          </AuthContext>
        </ThemeContext>
      </body>
    </html>
  );
}
